//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindows_WCF_CheckSalud.ProxyResultado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class ResultadoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomApePacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomEnfermedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float alturaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string audicionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAnalisisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEnfermedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codResultadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ekgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float pesoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psicologiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rayosXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recomendacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sangreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string spirometriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vistaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomApePaciente {
            get {
                return this.NomApePacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.NomApePacienteField, value) != true)) {
                    this.NomApePacienteField = value;
                    this.RaisePropertyChanged("NomApePaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomEnfermedad {
            get {
                return this.NomEnfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.NomEnfermedadField, value) != true)) {
                    this.NomEnfermedadField = value;
                    this.RaisePropertyChanged("NomEnfermedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float altura {
            get {
                return this.alturaField;
            }
            set {
                if ((this.alturaField.Equals(value) != true)) {
                    this.alturaField = value;
                    this.RaisePropertyChanged("altura");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string audicion {
            get {
                return this.audicionField;
            }
            set {
                if ((object.ReferenceEquals(this.audicionField, value) != true)) {
                    this.audicionField = value;
                    this.RaisePropertyChanged("audicion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAnalisis {
            get {
                return this.codAnalisisField;
            }
            set {
                if ((object.ReferenceEquals(this.codAnalisisField, value) != true)) {
                    this.codAnalisisField = value;
                    this.RaisePropertyChanged("codAnalisis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEnfermedad {
            get {
                return this.codEnfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.codEnfermedadField, value) != true)) {
                    this.codEnfermedadField = value;
                    this.RaisePropertyChanged("codEnfermedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEvaluacion {
            get {
                return this.codEvaluacionField;
            }
            set {
                if ((object.ReferenceEquals(this.codEvaluacionField, value) != true)) {
                    this.codEvaluacionField = value;
                    this.RaisePropertyChanged("codEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPaciente {
            get {
                return this.codPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.codPacienteField, value) != true)) {
                    this.codPacienteField = value;
                    this.RaisePropertyChanged("codPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codResultado {
            get {
                return this.codResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.codResultadoField, value) != true)) {
                    this.codResultadoField = value;
                    this.RaisePropertyChanged("codResultado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ekg {
            get {
                return this.ekgField;
            }
            set {
                if ((object.ReferenceEquals(this.ekgField, value) != true)) {
                    this.ekgField = value;
                    this.RaisePropertyChanged("ekg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orina {
            get {
                return this.orinaField;
            }
            set {
                if ((object.ReferenceEquals(this.orinaField, value) != true)) {
                    this.orinaField = value;
                    this.RaisePropertyChanged("orina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float peso {
            get {
                return this.pesoField;
            }
            set {
                if ((this.pesoField.Equals(value) != true)) {
                    this.pesoField = value;
                    this.RaisePropertyChanged("peso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psicologia {
            get {
                return this.psicologiaField;
            }
            set {
                if ((object.ReferenceEquals(this.psicologiaField, value) != true)) {
                    this.psicologiaField = value;
                    this.RaisePropertyChanged("psicologia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rayosX {
            get {
                return this.rayosXField;
            }
            set {
                if ((object.ReferenceEquals(this.rayosXField, value) != true)) {
                    this.rayosXField = value;
                    this.RaisePropertyChanged("rayosX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recomendaciones {
            get {
                return this.recomendacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.recomendacionesField, value) != true)) {
                    this.recomendacionesField = value;
                    this.RaisePropertyChanged("recomendaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sangre {
            get {
                return this.sangreField;
            }
            set {
                if ((object.ReferenceEquals(this.sangreField, value) != true)) {
                    this.sangreField = value;
                    this.RaisePropertyChanged("sangre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string spirometria {
            get {
                return this.spirometriaField;
            }
            set {
                if ((object.ReferenceEquals(this.spirometriaField, value) != true)) {
                    this.spirometriaField = value;
                    this.RaisePropertyChanged("spirometria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vista {
            get {
                return this.vistaField;
            }
            set {
                if ((object.ReferenceEquals(this.vistaField, value) != true)) {
                    this.vistaField = value;
                    this.RaisePropertyChanged("vista");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CboEnfermedadDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class CboEnfermedadDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEnfermedadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descEnfermedadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEnfermedad {
            get {
                return this.codEnfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.codEnfermedadField, value) != true)) {
                    this.codEnfermedadField = value;
                    this.RaisePropertyChanged("codEnfermedad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descEnfermedad {
            get {
                return this.descEnfermedadField;
            }
            set {
                if ((object.ReferenceEquals(this.descEnfermedadField, value) != true)) {
                    this.descEnfermedadField = value;
                    this.RaisePropertyChanged("descEnfermedad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CboPacienteDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class CboPacienteDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeNomPacienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codPacienteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNomPaciente {
            get {
                return this.ApeNomPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeNomPacienteField, value) != true)) {
                    this.ApeNomPacienteField = value;
                    this.RaisePropertyChanged("ApeNomPaciente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codPaciente {
            get {
                return this.codPacienteField;
            }
            set {
                if ((object.ReferenceEquals(this.codPacienteField, value) != true)) {
                    this.codPacienteField = value;
                    this.RaisePropertyChanged("codPaciente");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CboMedicoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class CboMedicoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeNomMedicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codMedicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNomMedico {
            get {
                return this.ApeNomMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeNomMedicoField, value) != true)) {
                    this.ApeNomMedicoField = value;
                    this.RaisePropertyChanged("ApeNomMedico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codMedico {
            get {
                return this.codMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.codMedicoField, value) != true)) {
                    this.codMedicoField = value;
                    this.RaisePropertyChanged("codMedico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CboAuditorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class CboAuditorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApeNomAuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAuditorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeNomAuditor {
            get {
                return this.ApeNomAuditorField;
            }
            set {
                if ((object.ReferenceEquals(this.ApeNomAuditorField, value) != true)) {
                    this.ApeNomAuditorField = value;
                    this.RaisePropertyChanged("ApeNomAuditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAuditor {
            get {
                return this.codAuditorField;
            }
            set {
                if ((object.ReferenceEquals(this.codAuditorField, value) != true)) {
                    this.codAuditorField = value;
                    this.RaisePropertyChanged("codAuditor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyResultado.IServicioResultado")]
    public interface IServicioResultado {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ConsultarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ConsultarResultadoResponse")]
        TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC ConsultarResultado(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ConsultarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ConsultarResultadoResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC> ConsultarResultadoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarResultados", ReplyAction="http://tempuri.org/IServicioResultado/ListarResultadosResponse")]
        TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC[] ListarResultados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarResultados", ReplyAction="http://tempuri.org/IServicioResultado/ListarResultadosResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC[]> ListarResultadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/InsertarResultado", ReplyAction="http://tempuri.org/IServicioResultado/InsertarResultadoResponse")]
        bool InsertarResultado(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/InsertarResultado", ReplyAction="http://tempuri.org/IServicioResultado/InsertarResultadoResponse")]
        System.Threading.Tasks.Task<bool> InsertarResultadoAsync(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ActualizarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ActualizarResultadoResponse")]
        bool ActualizarResultado(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ActualizarResultado", ReplyAction="http://tempuri.org/IServicioResultado/ActualizarResultadoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarResultadoAsync(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/EliminarResultado", ReplyAction="http://tempuri.org/IServicioResultado/EliminarResultadoResponse")]
        bool EliminarResultado(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/EliminarResultado", ReplyAction="http://tempuri.org/IServicioResultado/EliminarResultadoResponse")]
        System.Threading.Tasks.Task<bool> EliminarResultadoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarCboEnfermedad", ReplyAction="http://tempuri.org/IServicioResultado/ListarCboEnfermedadResponse")]
        TestWindows_WCF_CheckSalud.ProxyResultado.CboEnfermedadDC[] ListarCboEnfermedad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarCboEnfermedad", ReplyAction="http://tempuri.org/IServicioResultado/ListarCboEnfermedadResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboEnfermedadDC[]> ListarCboEnfermedadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarCboPaciente", ReplyAction="http://tempuri.org/IServicioResultado/ListarCboPacienteResponse")]
        TestWindows_WCF_CheckSalud.ProxyResultado.CboPacienteDC[] ListarCboPaciente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/ListarCboPaciente", ReplyAction="http://tempuri.org/IServicioResultado/ListarCboPacienteResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboPacienteDC[]> ListarCboPacienteAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/listarCboMedicoDC", ReplyAction="http://tempuri.org/IServicioResultado/listarCboMedicoDCResponse")]
        TestWindows_WCF_CheckSalud.ProxyResultado.CboMedicoDC[] listarCboMedicoDC();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/listarCboMedicoDC", ReplyAction="http://tempuri.org/IServicioResultado/listarCboMedicoDCResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboMedicoDC[]> listarCboMedicoDCAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/listarCboAuditores", ReplyAction="http://tempuri.org/IServicioResultado/listarCboAuditoresResponse")]
        TestWindows_WCF_CheckSalud.ProxyResultado.CboAuditorDC[] listarCboAuditores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioResultado/listarCboAuditores", ReplyAction="http://tempuri.org/IServicioResultado/listarCboAuditoresResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboAuditorDC[]> listarCboAuditoresAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioResultadoChannel : TestWindows_WCF_CheckSalud.ProxyResultado.IServicioResultado, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioResultadoClient : System.ServiceModel.ClientBase<TestWindows_WCF_CheckSalud.ProxyResultado.IServicioResultado>, TestWindows_WCF_CheckSalud.ProxyResultado.IServicioResultado {
        
        public ServicioResultadoClient() {
        }
        
        public ServicioResultadoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioResultadoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResultadoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioResultadoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC ConsultarResultado(string strCodigo) {
            return base.Channel.ConsultarResultado(strCodigo);
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC> ConsultarResultadoAsync(string strCodigo) {
            return base.Channel.ConsultarResultadoAsync(strCodigo);
        }
        
        public TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC[] ListarResultados() {
            return base.Channel.ListarResultados();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC[]> ListarResultadosAsync() {
            return base.Channel.ListarResultadosAsync();
        }
        
        public bool InsertarResultado(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.InsertarResultado(objResultadoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarResultadoAsync(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.InsertarResultadoAsync(objResultadoDC);
        }
        
        public bool ActualizarResultado(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.ActualizarResultado(objResultadoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarResultadoAsync(TestWindows_WCF_CheckSalud.ProxyResultado.ResultadoDC objResultadoDC) {
            return base.Channel.ActualizarResultadoAsync(objResultadoDC);
        }
        
        public bool EliminarResultado(string strCodigo) {
            return base.Channel.EliminarResultado(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarResultadoAsync(string strCodigo) {
            return base.Channel.EliminarResultadoAsync(strCodigo);
        }
        
        public TestWindows_WCF_CheckSalud.ProxyResultado.CboEnfermedadDC[] ListarCboEnfermedad() {
            return base.Channel.ListarCboEnfermedad();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboEnfermedadDC[]> ListarCboEnfermedadAsync() {
            return base.Channel.ListarCboEnfermedadAsync();
        }
        
        public TestWindows_WCF_CheckSalud.ProxyResultado.CboPacienteDC[] ListarCboPaciente() {
            return base.Channel.ListarCboPaciente();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboPacienteDC[]> ListarCboPacienteAsync() {
            return base.Channel.ListarCboPacienteAsync();
        }
        
        public TestWindows_WCF_CheckSalud.ProxyResultado.CboMedicoDC[] listarCboMedicoDC() {
            return base.Channel.listarCboMedicoDC();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboMedicoDC[]> listarCboMedicoDCAsync() {
            return base.Channel.listarCboMedicoDCAsync();
        }
        
        public TestWindows_WCF_CheckSalud.ProxyResultado.CboAuditorDC[] listarCboAuditores() {
            return base.Channel.listarCboAuditores();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyResultado.CboAuditorDC[]> listarCboAuditoresAsync() {
            return base.Channel.listarCboAuditoresAsync();
        }
    }
}
