//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using DotNetEnv;
    using System;
    using System.Configuration;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    

    public partial class CheckSaludEntities : DbContext
    {
        public CheckSaludEntities()
            : base("name=CheckSaludEntities")
        { }
        private static string GetConnectionString()
        {
            DotNetEnv.Env.Load(); // Cargar las variables de entorno desde el archivo .env
            DotNetEnv.Env.TraversePath().Load();

            String connectionString = DotNetEnv.Env.GetString("DB_CONNECTION_STRING");
            // Realiza cualquier otra manipulación necesaria en la cadena de conexión si es necesario

            return connectionString;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Analisis> Tb_Analisis { get; set; }
        public virtual DbSet<Tb_Auditor> Tb_Auditor { get; set; }
        public virtual DbSet<Tb_DocumentoPac> Tb_DocumentoPac { get; set; }
        public virtual DbSet<Tb_Empresa> Tb_Empresa { get; set; }
        public virtual DbSet<Tb_Enfermedad> Tb_Enfermedad { get; set; }
        public virtual DbSet<Tb_Especialidad> Tb_Especialidad { get; set; }
        public virtual DbSet<Tb_Evaluacion> Tb_Evaluacion { get; set; }
        public virtual DbSet<Tb_Medico> Tb_Medico { get; set; }
        public virtual DbSet<Tb_Paciente> Tb_Paciente { get; set; }
        public virtual DbSet<Tb_Resultados> Tb_Resultados { get; set; }
        public virtual DbSet<Tb_Ubicacion> Tb_Ubicacion { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual int usp_InsertarResultado(Nullable<decimal> vPeso, Nullable<decimal> vAltura, string vSangre, string vOrina, string vEkg, string vSpiro, string vPsico, string vXray, string vAudi, string vVisi, string vCodAnal, string vCodEva, string vCodEnfe, string vRecom, string vCodPac, string vUsu_Registro)
        {
            var vPesoParameter = vPeso.HasValue ?
                new ObjectParameter("vPeso", vPeso) :
                new ObjectParameter("vPeso", typeof(decimal));
    
            var vAlturaParameter = vAltura.HasValue ?
                new ObjectParameter("vAltura", vAltura) :
                new ObjectParameter("vAltura", typeof(decimal));
    
            var vSangreParameter = vSangre != null ?
                new ObjectParameter("vSangre", vSangre) :
                new ObjectParameter("vSangre", typeof(string));
    
            var vOrinaParameter = vOrina != null ?
                new ObjectParameter("vOrina", vOrina) :
                new ObjectParameter("vOrina", typeof(string));
    
            var vEkgParameter = vEkg != null ?
                new ObjectParameter("vEkg", vEkg) :
                new ObjectParameter("vEkg", typeof(string));
    
            var vSpiroParameter = vSpiro != null ?
                new ObjectParameter("vSpiro", vSpiro) :
                new ObjectParameter("vSpiro", typeof(string));
    
            var vPsicoParameter = vPsico != null ?
                new ObjectParameter("vPsico", vPsico) :
                new ObjectParameter("vPsico", typeof(string));
    
            var vXrayParameter = vXray != null ?
                new ObjectParameter("vXray", vXray) :
                new ObjectParameter("vXray", typeof(string));
    
            var vAudiParameter = vAudi != null ?
                new ObjectParameter("vAudi", vAudi) :
                new ObjectParameter("vAudi", typeof(string));
    
            var vVisiParameter = vVisi != null ?
                new ObjectParameter("vVisi", vVisi) :
                new ObjectParameter("vVisi", typeof(string));
    
            var vCodAnalParameter = vCodAnal != null ?
                new ObjectParameter("vCodAnal", vCodAnal) :
                new ObjectParameter("vCodAnal", typeof(string));
    
            var vCodEvaParameter = vCodEva != null ?
                new ObjectParameter("vCodEva", vCodEva) :
                new ObjectParameter("vCodEva", typeof(string));
    
            var vCodEnfeParameter = vCodEnfe != null ?
                new ObjectParameter("vCodEnfe", vCodEnfe) :
                new ObjectParameter("vCodEnfe", typeof(string));
    
            var vRecomParameter = vRecom != null ?
                new ObjectParameter("vRecom", vRecom) :
                new ObjectParameter("vRecom", typeof(string));
    
            var vCodPacParameter = vCodPac != null ?
                new ObjectParameter("vCodPac", vCodPac) :
                new ObjectParameter("vCodPac", typeof(string));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarResultado", vPesoParameter, vAlturaParameter, vSangreParameter, vOrinaParameter, vEkgParameter, vSpiroParameter, vPsicoParameter, vXrayParameter, vAudiParameter, vVisiParameter, vCodAnalParameter, vCodEvaParameter, vCodEnfeParameter, vRecomParameter, vCodPacParameter, vUsu_RegistroParameter);
        }
    
        public virtual int usp_ActualizarResultado(string vCod, Nullable<decimal> vPeso, Nullable<decimal> vAltura, string vSangre, string vOrina, string vEkg, string vSpiro, string vPsico, string vXray, string vAudi, string vVisi, string vCodEnfe, string vRecom, string vCodPac, string vUsu_Ult_Mod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            var vPesoParameter = vPeso.HasValue ?
                new ObjectParameter("vPeso", vPeso) :
                new ObjectParameter("vPeso", typeof(decimal));
    
            var vAlturaParameter = vAltura.HasValue ?
                new ObjectParameter("vAltura", vAltura) :
                new ObjectParameter("vAltura", typeof(decimal));
    
            var vSangreParameter = vSangre != null ?
                new ObjectParameter("vSangre", vSangre) :
                new ObjectParameter("vSangre", typeof(string));
    
            var vOrinaParameter = vOrina != null ?
                new ObjectParameter("vOrina", vOrina) :
                new ObjectParameter("vOrina", typeof(string));
    
            var vEkgParameter = vEkg != null ?
                new ObjectParameter("vEkg", vEkg) :
                new ObjectParameter("vEkg", typeof(string));
    
            var vSpiroParameter = vSpiro != null ?
                new ObjectParameter("vSpiro", vSpiro) :
                new ObjectParameter("vSpiro", typeof(string));
    
            var vPsicoParameter = vPsico != null ?
                new ObjectParameter("vPsico", vPsico) :
                new ObjectParameter("vPsico", typeof(string));
    
            var vXrayParameter = vXray != null ?
                new ObjectParameter("vXray", vXray) :
                new ObjectParameter("vXray", typeof(string));
    
            var vAudiParameter = vAudi != null ?
                new ObjectParameter("vAudi", vAudi) :
                new ObjectParameter("vAudi", typeof(string));
    
            var vVisiParameter = vVisi != null ?
                new ObjectParameter("vVisi", vVisi) :
                new ObjectParameter("vVisi", typeof(string));
    
            var vCodEnfeParameter = vCodEnfe != null ?
                new ObjectParameter("vCodEnfe", vCodEnfe) :
                new ObjectParameter("vCodEnfe", typeof(string));
    
            var vRecomParameter = vRecom != null ?
                new ObjectParameter("vRecom", vRecom) :
                new ObjectParameter("vRecom", typeof(string));
    
            var vCodPacParameter = vCodPac != null ?
                new ObjectParameter("vCodPac", vCodPac) :
                new ObjectParameter("vCodPac", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarResultado", vCodParameter, vPesoParameter, vAlturaParameter, vSangreParameter, vOrinaParameter, vEkgParameter, vSpiroParameter, vPsicoParameter, vXrayParameter, vAudiParameter, vVisiParameter, vCodEnfeParameter, vRecomParameter, vCodPacParameter, vUsu_Ult_ModParameter);
        }
    
        public virtual int usp_EliminarResultado(string vCod)
        {
            var vCodParameter = vCod != null ?
                new ObjectParameter("vCod", vCod) :
                new ObjectParameter("vCod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarResultado", vCodParameter);
        }
    
        public virtual int usp_InsertarAnalisis(string vDes, Nullable<decimal> vCos, Nullable<int> vEst, string vUsu_Reg)
        {
            var vDesParameter = vDes != null ?
                new ObjectParameter("vDes", vDes) :
                new ObjectParameter("vDes", typeof(string));
    
            var vCosParameter = vCos.HasValue ?
                new ObjectParameter("vCos", vCos) :
                new ObjectParameter("vCos", typeof(decimal));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(int));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarAnalisis", vDesParameter, vCosParameter, vEstParameter, vUsu_RegParameter);
        }
    
        public virtual int usp_InsertarEvaluacion(Nullable<System.DateTime> vFEva, string vMed, string vAud, Nullable<int> vEst, string vUsu_Reg)
        {
            var vFEvaParameter = vFEva.HasValue ?
                new ObjectParameter("vFEva", vFEva) :
                new ObjectParameter("vFEva", typeof(System.DateTime));
    
            var vMedParameter = vMed != null ?
                new ObjectParameter("vMed", vMed) :
                new ObjectParameter("vMed", typeof(string));
    
            var vAudParameter = vAud != null ?
                new ObjectParameter("vAud", vAud) :
                new ObjectParameter("vAud", typeof(string));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(int));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEvaluacion", vFEvaParameter, vMedParameter, vAudParameter, vEstParameter, vUsu_RegParameter);
        }
    
        public virtual int usp_ActualizarMedico(string vCodMedico, string dniMedic, string nomMedico, string apeMedico, string numColegiatura, Nullable<System.DateTime> fechaNacimiento, string emailMedico, string direcMedico, Nullable<int> estado, string codEspecialidad, string login_Usuario, string usu_Ult_Mod, string id_Ubigeo)
        {
            var vCodMedicoParameter = vCodMedico != null ?
                new ObjectParameter("vCodMedico", vCodMedico) :
                new ObjectParameter("vCodMedico", typeof(string));
    
            var dniMedicParameter = dniMedic != null ?
                new ObjectParameter("dniMedic", dniMedic) :
                new ObjectParameter("dniMedic", typeof(string));
    
            var nomMedicoParameter = nomMedico != null ?
                new ObjectParameter("nomMedico", nomMedico) :
                new ObjectParameter("nomMedico", typeof(string));
    
            var apeMedicoParameter = apeMedico != null ?
                new ObjectParameter("apeMedico", apeMedico) :
                new ObjectParameter("apeMedico", typeof(string));
    
            var numColegiaturaParameter = numColegiatura != null ?
                new ObjectParameter("numColegiatura", numColegiatura) :
                new ObjectParameter("numColegiatura", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("fechaNacimiento", fechaNacimiento) :
                new ObjectParameter("fechaNacimiento", typeof(System.DateTime));
    
            var emailMedicoParameter = emailMedico != null ?
                new ObjectParameter("emailMedico", emailMedico) :
                new ObjectParameter("emailMedico", typeof(string));
    
            var direcMedicoParameter = direcMedico != null ?
                new ObjectParameter("direcMedico", direcMedico) :
                new ObjectParameter("direcMedico", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var codEspecialidadParameter = codEspecialidad != null ?
                new ObjectParameter("codEspecialidad", codEspecialidad) :
                new ObjectParameter("codEspecialidad", typeof(string));
    
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarMedico", vCodMedicoParameter, dniMedicParameter, nomMedicoParameter, apeMedicoParameter, numColegiaturaParameter, fechaNacimientoParameter, emailMedicoParameter, direcMedicoParameter, estadoParameter, codEspecialidadParameter, login_UsuarioParameter, usu_Ult_ModParameter, id_UbigeoParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarMedico_Result> usp_ConsultarMedico(string vCodMedico)
        {
            var vCodMedicoParameter = vCodMedico != null ?
                new ObjectParameter("vCodMedico", vCodMedico) :
                new ObjectParameter("vCodMedico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarMedico_Result>("usp_ConsultarMedico", vCodMedicoParameter);
        }
    
        public virtual int usp_EliminarMedico(string vcodMedico)
        {
            var vcodMedicoParameter = vcodMedico != null ?
                new ObjectParameter("VcodMedico", vcodMedico) :
                new ObjectParameter("VcodMedico", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarMedico", vcodMedicoParameter);
        }
    
        public virtual int usp_InsertarMedico(string dniMedic, string nomMedico, string apeMedico, string numColegiatura, Nullable<System.DateTime> fechaNacimiento, string emailMedico, string direcMedico, Nullable<int> estado, string codEspecialidad, string login_Usuario, string usu_Registro, string id_Ubigeo, Nullable<System.DateTime> fec_ingreso)
        {
            var dniMedicParameter = dniMedic != null ?
                new ObjectParameter("dniMedic", dniMedic) :
                new ObjectParameter("dniMedic", typeof(string));
    
            var nomMedicoParameter = nomMedico != null ?
                new ObjectParameter("nomMedico", nomMedico) :
                new ObjectParameter("nomMedico", typeof(string));
    
            var apeMedicoParameter = apeMedico != null ?
                new ObjectParameter("apeMedico", apeMedico) :
                new ObjectParameter("apeMedico", typeof(string));
    
            var numColegiaturaParameter = numColegiatura != null ?
                new ObjectParameter("numColegiatura", numColegiatura) :
                new ObjectParameter("numColegiatura", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento.HasValue ?
                new ObjectParameter("fechaNacimiento", fechaNacimiento) :
                new ObjectParameter("fechaNacimiento", typeof(System.DateTime));
    
            var emailMedicoParameter = emailMedico != null ?
                new ObjectParameter("emailMedico", emailMedico) :
                new ObjectParameter("emailMedico", typeof(string));
    
            var direcMedicoParameter = direcMedico != null ?
                new ObjectParameter("direcMedico", direcMedico) :
                new ObjectParameter("direcMedico", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(int));
    
            var codEspecialidadParameter = codEspecialidad != null ?
                new ObjectParameter("codEspecialidad", codEspecialidad) :
                new ObjectParameter("codEspecialidad", typeof(string));
    
            var login_UsuarioParameter = login_Usuario != null ?
                new ObjectParameter("Login_Usuario", login_Usuario) :
                new ObjectParameter("Login_Usuario", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var fec_ingresoParameter = fec_ingreso.HasValue ?
                new ObjectParameter("fec_ingreso", fec_ingreso) :
                new ObjectParameter("fec_ingreso", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarMedico", dniMedicParameter, nomMedicoParameter, apeMedicoParameter, numColegiaturaParameter, fechaNacimientoParameter, emailMedicoParameter, direcMedicoParameter, estadoParameter, codEspecialidadParameter, login_UsuarioParameter, usu_RegistroParameter, id_UbigeoParameter, fec_ingresoParameter);
        }
    
        public virtual ObjectResult<usp_ListarMedico_Result> usp_ListarMedico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarMedico_Result>("usp_ListarMedico");
        }
    }
}
