//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DocumentoPac
    {
        public int codDocumento { get; set; }
        public byte[] img_sangre { get; set; }
        public byte[] img_orina { get; set; }
        public byte[] img_ekg { get; set; }
        public byte[] img_spirometria { get; set; }
        public byte[] img_psicologia { get; set; }
        public byte[] img_rayosX { get; set; }
        public byte[] img_audicion { get; set; }
        public byte[] img_vista { get; set; }
        public string Login_Usuario { get; set; }
        public string codPaciente { get; set; }
    
        public virtual Tb_Paciente Tb_Paciente { get; set; }
        public virtual Tb_Usuario Tb_Usuario { get; set; }
    }
}
