//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_DocumentoPac
    {
        public int codDocumento { get; set; }
        public byte[] img_sangre { get; set; }
        public byte[] img_orina { get; set; }
        public byte[] img_ekg { get; set; }
        public byte[] img_spirometria { get; set; }
        public byte[] img_psicologia { get; set; }
        public byte[] img_rayosX { get; set; }
        public byte[] img_audicion { get; set; }
        public byte[] img_vista { get; set; }
        public string Login_Usuario { get; set; }
        public string codPaciente { get; set; }
    
        public virtual Tb_Paciente Tb_Paciente { get; set; }
        public virtual Tb_Usuario Tb_Usuario { get; set; }
    }
}
