//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Empresa_Aud
    {
        public string codEmpresa { get; set; }
        public string Raz_soc_emp { get; set; }
        public string Dir_emp { get; set; }
        public string Tel_emp { get; set; }
        public string Ruc_emp { get; set; }
        public string Rep_emp { get; set; }
        public string Id_Ubigeo { get; set; }
        public Nullable<System.DateTime> fec_Ingreso { get; set; }
        public int estado { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> FechaAccion { get; set; }
    }
}
