//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Medico_Aud
    {
        public string codMedico { get; set; }
        public string dniMedic { get; set; }
        public string nomMedico { get; set; }
        public string apeMedico { get; set; }
        public string numColegiatura { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string emailMedico { get; set; }
        public byte[] fotoMedico { get; set; }
        public string direcMedico { get; set; }
        public int estado { get; set; }
        public string codEspecialidad { get; set; }
        public string Login_Usuario { get; set; }
        public Nullable<System.DateTime> Fec_Reg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fech_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string Id_Ubigeo { get; set; }
        public Nullable<System.DateTime> fec_ingreso { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> FechaAccion { get; set; }
    }
}
