//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Medico
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Medico()
        {
            this.Tb_Auditor = new HashSet<Tb_Auditor>();
            this.Tb_Evaluacion = new HashSet<Tb_Evaluacion>();
        }
    
        public string codMedico { get; set; }
        public string dniMedic { get; set; }
        public string nomMedico { get; set; }
        public string apeMedico { get; set; }
        public string numColegiatura { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string emailMedico { get; set; }
        public byte[] fotoMedico { get; set; }
        public string direcMedico { get; set; }
        public int estado { get; set; }
        public string codEspecialidad { get; set; }
        public string Login_Usuario { get; set; }
        public Nullable<System.DateTime> Fec_Reg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fech_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string Id_Ubigeo { get; set; }
        public Nullable<System.DateTime> fec_ingreso { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Auditor> Tb_Auditor { get; set; }
        public virtual Tb_Especialidad Tb_Especialidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Evaluacion> Tb_Evaluacion { get; set; }
        public virtual Tb_Ubicacion Tb_Ubicacion { get; set; }
        public virtual Tb_Usuario Tb_Usuario { get; set; }
    }
}
