//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Resultados_Aud
    {
        public string codResultado { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> altura { get; set; }
        public string sangre { get; set; }
        public string orina { get; set; }
        public string ekg { get; set; }
        public string spirometria { get; set; }
        public string psicologia { get; set; }
        public string rayosX { get; set; }
        public string audicion { get; set; }
        public string vista { get; set; }
        public string codAnalisis { get; set; }
        public string codEvaluacion { get; set; }
        public string codEnfermedad { get; set; }
        public string recomendaciones { get; set; }
        public string codPaciente { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string Accion { get; set; }
        public Nullable<System.DateTime> FechaAccion { get; set; }
    }
}
