//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Resultados
    {
        public string codResultado { get; set; }
        public Nullable<double> peso { get; set; }
        public Nullable<double> altura { get; set; }
        public string sangre { get; set; }
        public string orina { get; set; }
        public string ekg { get; set; }
        public string spirometria { get; set; }
        public string psicologia { get; set; }
        public string rayosX { get; set; }
        public string audicion { get; set; }
        public string vista { get; set; }
        public string codAnalisis { get; set; }
        public string codEvaluacion { get; set; }
        public string codEnfermedad { get; set; }
        public string recomendaciones { get; set; }
        public string codPaciente { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
    
        public virtual Tb_Analisis Tb_Analisis { get; set; }
        public virtual Tb_Enfermedad Tb_Enfermedad { get; set; }
        public virtual Tb_Evaluacion Tb_Evaluacion { get; set; }
        public virtual Tb_Paciente Tb_Paciente { get; set; }
    }
}
