//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaPacienteEstado
    {
        public string codPaciente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Genero { get; set; }
        public string Lugar_de_trabajo { get; set; }
        public string telefono { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string Dni { get; set; }
        public string Dirección { get; set; }
        public string estado { get; set; }
        public string Tipo_Cliente { get; set; }
        public Nullable<int> Cantidad_de_evaluaciones { get; set; }
    }
}
