//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_CheckSalud
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaAnalisisEstado
    {
        public string codAnalisis { get; set; }
        public string NombrePaciente { get; set; }
        public string ApellidoPaciente { get; set; }
        public string Lugar_de_trabajo { get; set; }
        public string TipoAnális { get; set; }
        public Nullable<decimal> CostoAnálisis { get; set; }
        public Nullable<System.DateTime> FechaEvaluacion { get; set; }
        public string Estado { get; set; }
    }
}
