//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindows_WCF_CheckSalud.ProxyEspecialidad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EspecialidadDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class EspecialidadDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descEspecialidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEspecialidad {
            get {
                return this.codEspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.codEspecialidadField, value) != true)) {
                    this.codEspecialidadField = value;
                    this.RaisePropertyChanged("codEspecialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descEspecialidad {
            get {
                return this.descEspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.descEspecialidadField, value) != true)) {
                    this.descEspecialidadField = value;
                    this.RaisePropertyChanged("descEspecialidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEspecialidad.IServicioEspecialidad")]
    public interface IServicioEspecialidad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEspecialidad/ListarEspecialidad", ReplyAction="http://tempuri.org/IServicioEspecialidad/ListarEspecialidadResponse")]
        TestWindows_WCF_CheckSalud.ProxyEspecialidad.EspecialidadDC[] ListarEspecialidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEspecialidad/ListarEspecialidad", ReplyAction="http://tempuri.org/IServicioEspecialidad/ListarEspecialidadResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyEspecialidad.EspecialidadDC[]> ListarEspecialidadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEspecialidadChannel : TestWindows_WCF_CheckSalud.ProxyEspecialidad.IServicioEspecialidad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEspecialidadClient : System.ServiceModel.ClientBase<TestWindows_WCF_CheckSalud.ProxyEspecialidad.IServicioEspecialidad>, TestWindows_WCF_CheckSalud.ProxyEspecialidad.IServicioEspecialidad {
        
        public ServicioEspecialidadClient() {
        }
        
        public ServicioEspecialidadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEspecialidadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEspecialidadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEspecialidadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestWindows_WCF_CheckSalud.ProxyEspecialidad.EspecialidadDC[] ListarEspecialidad() {
            return base.Channel.ListarEspecialidad();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyEspecialidad.EspecialidadDC[]> ListarEspecialidadAsync() {
            return base.Channel.ListarEspecialidadAsync();
        }
    }
}
