//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindows_WCF_CheckSalud.ProxyAnalisis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnalisisDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class AnalisisDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAnalisisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double costoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descAnalisisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAnalisis {
            get {
                return this.codAnalisisField;
            }
            set {
                if ((object.ReferenceEquals(this.codAnalisisField, value) != true)) {
                    this.codAnalisisField = value;
                    this.RaisePropertyChanged("codAnalisis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double costo {
            get {
                return this.costoField;
            }
            set {
                if ((this.costoField.Equals(value) != true)) {
                    this.costoField = value;
                    this.RaisePropertyChanged("costo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descAnalisis {
            get {
                return this.descAnalisisField;
            }
            set {
                if ((object.ReferenceEquals(this.descAnalisisField, value) != true)) {
                    this.descAnalisisField = value;
                    this.RaisePropertyChanged("descAnalisis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAnalisis.IServicioAnalisis")]
    public interface IServicioAnalisis {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/InsertarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/InsertarAnalisisResponse")]
        bool InsertarAnalisis(TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC objAnalisisDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/InsertarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/InsertarAnalisisResponse")]
        System.Threading.Tasks.Task<bool> InsertarAnalisisAsync(TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC objAnalisisDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ConsultarUltAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ConsultarUltAnalisisResponse")]
        TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC ConsultarUltAnalisis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ConsultarUltAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ConsultarUltAnalisisResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC> ConsultarUltAnalisisAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ListarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ListarAnalisisResponse")]
        TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC[] ListarAnalisis();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAnalisis/ListarAnalisis", ReplyAction="http://tempuri.org/IServicioAnalisis/ListarAnalisisResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC[]> ListarAnalisisAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioAnalisisChannel : TestWindows_WCF_CheckSalud.ProxyAnalisis.IServicioAnalisis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioAnalisisClient : System.ServiceModel.ClientBase<TestWindows_WCF_CheckSalud.ProxyAnalisis.IServicioAnalisis>, TestWindows_WCF_CheckSalud.ProxyAnalisis.IServicioAnalisis {
        
        public ServicioAnalisisClient() {
        }
        
        public ServicioAnalisisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioAnalisisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAnalisisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioAnalisisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarAnalisis(TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC objAnalisisDC) {
            return base.Channel.InsertarAnalisis(objAnalisisDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAnalisisAsync(TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC objAnalisisDC) {
            return base.Channel.InsertarAnalisisAsync(objAnalisisDC);
        }
        
        public TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC ConsultarUltAnalisis() {
            return base.Channel.ConsultarUltAnalisis();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC> ConsultarUltAnalisisAsync() {
            return base.Channel.ConsultarUltAnalisisAsync();
        }
        
        public TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC[] ListarAnalisis() {
            return base.Channel.ListarAnalisis();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyAnalisis.AnalisisDC[]> ListarAnalisisAsync() {
            return base.Channel.ListarAnalisisAsync();
        }
    }
}
