//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWindows_WCF_CheckSalud.ProxyEvaluacion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EvaluacionDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_CheckSalud")]
    [System.SerializableAttribute()]
    public partial class EvaluacionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Fec_EvaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codAuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codEvaluacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codMedicoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fec_Eva {
            get {
                return this.Fec_EvaField;
            }
            set {
                if ((object.ReferenceEquals(this.Fec_EvaField, value) != true)) {
                    this.Fec_EvaField = value;
                    this.RaisePropertyChanged("Fec_Eva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codAuditor {
            get {
                return this.codAuditorField;
            }
            set {
                if ((object.ReferenceEquals(this.codAuditorField, value) != true)) {
                    this.codAuditorField = value;
                    this.RaisePropertyChanged("codAuditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codEvaluacion {
            get {
                return this.codEvaluacionField;
            }
            set {
                if ((object.ReferenceEquals(this.codEvaluacionField, value) != true)) {
                    this.codEvaluacionField = value;
                    this.RaisePropertyChanged("codEvaluacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codMedico {
            get {
                return this.codMedicoField;
            }
            set {
                if ((object.ReferenceEquals(this.codMedicoField, value) != true)) {
                    this.codMedicoField = value;
                    this.RaisePropertyChanged("codMedico");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyEvaluacion.IServicioEvaluacion")]
    public interface IServicioEvaluacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacionResponse")]
        bool InsertarEvaluacion(TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/InsertarEvaluacionResponse")]
        System.Threading.Tasks.Task<bool> InsertarEvaluacionAsync(TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/ConsultarUltEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/ConsultarUltEvaluacionResponse")]
        TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC ConsultarUltEvaluacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/ConsultarUltEvaluacion", ReplyAction="http://tempuri.org/IServicioEvaluacion/ConsultarUltEvaluacionResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC> ConsultarUltEvaluacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/ListarEvalucion", ReplyAction="http://tempuri.org/IServicioEvaluacion/ListarEvalucionResponse")]
        TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC[] ListarEvalucion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioEvaluacion/ListarEvalucion", ReplyAction="http://tempuri.org/IServicioEvaluacion/ListarEvalucionResponse")]
        System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC[]> ListarEvalucionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioEvaluacionChannel : TestWindows_WCF_CheckSalud.ProxyEvaluacion.IServicioEvaluacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioEvaluacionClient : System.ServiceModel.ClientBase<TestWindows_WCF_CheckSalud.ProxyEvaluacion.IServicioEvaluacion>, TestWindows_WCF_CheckSalud.ProxyEvaluacion.IServicioEvaluacion {
        
        public ServicioEvaluacionClient() {
        }
        
        public ServicioEvaluacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioEvaluacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEvaluacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioEvaluacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool InsertarEvaluacion(TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC) {
            return base.Channel.InsertarEvaluacion(objEvaluacionDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarEvaluacionAsync(TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC objEvaluacionDC) {
            return base.Channel.InsertarEvaluacionAsync(objEvaluacionDC);
        }
        
        public TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC ConsultarUltEvaluacion() {
            return base.Channel.ConsultarUltEvaluacion();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC> ConsultarUltEvaluacionAsync() {
            return base.Channel.ConsultarUltEvaluacionAsync();
        }
        
        public TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC[] ListarEvalucion() {
            return base.Channel.ListarEvalucion();
        }
        
        public System.Threading.Tasks.Task<TestWindows_WCF_CheckSalud.ProxyEvaluacion.EvaluacionDC[]> ListarEvalucionAsync() {
            return base.Channel.ListarEvalucionAsync();
        }
    }
}
